apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: gcr.io/river-nectar-360800/github.com/costapauloedu/mitigacao-ddos
        name: webapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /test
            port: 80
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /test
            port: 80
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 8
        readinessProbe:
          httpGet:
            path: /test
            port: 80
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 8
